### ISSUE TITLE
Missile Domination and Jr. Pac-Man are partially working, but don't show sprites

### ISSUE THREAD

**Issue by Brianvgplayer** [MiSTer-devel/Intv_MiSTer#15]
Both of these homebrew games boot up, but sprites in both games don't show up. The select icon for Jr. Pac-Man doesn't show up, sprites don't show up on demo screens, and I can't start a game. In Missile Domination, a missile command clone that was once available on the AtariAge forum, I can start a game, but the missiles don't show up and the cities destroy themselves. I can vouch for Jr. Pac-Man working on real hardware since I have purchased both the rom and the cart for that game.

**Comment by zachmayer** [comment]
Try turning off ECS and intellivoice?

**Comment by Brianvgplayer** [comment]
Yes, didn't fix the issue.

**Comment by Grabulosaure** [comment]
Fixed for Missile, don't know for the other one.

**Comment by Brianvgplayer** [comment]
Tested both games with the new build from discord. Jr. Pac-Man and both versions of Missile Domination work great!
