### ISSUE TITLE
Games do not launch using Aug 9 release

### ISSUE THREAD

**Issue by mario-64** [MiSTer-devel/Intv_MiSTer#9]
Just installed the new Aug 9 core and no games launch at all. Tried many official games and it just sits at a blank screen.

**Comment by Kitrinx** [comment]
You are likely either missing the bootrom files (check the readme) or using the wrong file format. Files should have no header, ie be 8kb not 9kb, etc.

**Comment by mario-64** [comment]
Thanks Kitrinx. Wouldn't update_all get the correct file?

**Comment by Kitrinx** [comment]
I don't know what update_all does. It's possible that script does not yet have intellivision's needs covered as it was just released today.
